import { TicketInformationStateType } from "../../ticketDetails/components";

export const TestTicket: TicketInformationStateType[] = [
  {
    firstParty: "CEVA",
    shipper: {
      company: "Walmart1",
      name: "Derek",
      address: "123 Yonge St",
      phoneNum: "1234567890",
      postalCode: "A1B, 2C3",
    },
    shipmentDetails: {
      refNum: "12312312312",
      barcode: "123123123123",
      numPieces: "1",
      weight: "2",
      bolNum: "999999999",
      specialInst: "",
    },
    consignee: {
      company: "Popeyes",
      name: "Eric",
      address: "321 Bathurst St",
      phoneNum: "0987654321",
      postalCode: "H1B, 1A3",
    },
    enterIntoInventory: false,
    isPickup: true,
    noSignatureRequired: true,
    tailgateAuthorized: true,
  },
  {
    firstParty: "CEVA",
    shipper: {
      company: "Walmart2",
      name: "Derek",
      address: "123 Yonge St",
      phoneNum: "1234567890",
      postalCode: "A1B, 2C3",
    },
    shipmentDetails: {
      refNum: "12312312312",
      barcode: "123123123123",
      numPieces: "1",
      weight: "2",
      bolNum: "999999999",
      specialInst: "",
    },
    consignee: {
      company: "Popeyes",
      name: "Eric",
      address: "321 Bathurst St",
      phoneNum: "0987654321",
      postalCode: "H1B, 1A3",
    },
    enterIntoInventory: false,
    isPickup: true,
    noSignatureRequired: true,
    tailgateAuthorized: false,
  },
  {
    firstParty: "CEVA",
    shipper: {
      company: "Walmart3",
      name: "Derek",
      address: "123 Yonge St",
      phoneNum: "1234567890",
      postalCode: "A1B, 2C3",
    },
    shipmentDetails: {
      refNum: "12312312312",
      barcode: "123123123123",
      numPieces: "1",
      weight: "2",
      bolNum: "999999999",
      specialInst: "",
    },
    consignee: {
      company: "Popeyes",
      name: "Eric",
      address: "321 Bathurst St",
      phoneNum: "0987654321",
      postalCode: "H1B, 1A3",
    },
    enterIntoInventory: false,
    isPickup: true,
    noSignatureRequired: false,
    tailgateAuthorized: true,
  },
];
