import { RowType } from "../components/ticketTable";
import { Keys } from "../components/allTicketTableHeaders";

export const TestRows: RowType<Keys>[] = [
  {
    date: "2022/02/12",
    // status: "Delivered",
    firstParty: "CEVA",
    consigneeName: "FRANKE",
    consigneeAddress: "224 Wilson Avenue",
    // lastAssigned: "Rahul",
    barcodeNumber: "DG104-123456",
    shipper: "Amazon",
    pickup: "1",
    ticketId: "1",
  },
  {
    date: "2022/02/12",
    // status: "Delivered",
    firstParty: "CEVA",
    consigneeName: "FRANKE",
    consigneeAddress: "224 Wilson Avenue",
    // lastAssigned: "Rahul",
    barcodeNumber: "DG104-123456",
    shipper: "Amazon",
    pickup: "0",
    ticketId: "2",
  },
  {
    date: "2022/02/12",
    // status: "Delivered",
    firstParty: "CEVA",
    consigneeName: "FRANKE",
    consigneeAddress: "224 Wilson Avenue",
    // lastAssigned: "Rahul",
    barcodeNumber: "DG104-123456",
    shipper: "Amazon",
    pickup: "1",
    ticketId: "3",
  },
  {
    date: "2022/02/12",
    // status: "Delivered",
    firstParty: "CEVA",
    consigneeName: "FRANKE",
    consigneeAddress: "224 Wilson Avenue",
    // lastAssigned: "Rahul",
    barcodeNumber: "DG104-123456",
    shipper: "Amazon",
    pickup: "0",
    ticketId: "4",
  },
  {
    date: "2022/02/12",
    // status: "Delivered",
    firstParty: "CEVA",
    consigneeName: "FRANKE",
    consigneeAddress: "224 Wilson Avenue",
    // lastAssigned: "Rahul",
    barcodeNumber: "DG104-123456",
    shipper: "Amazon",
    pickup: "1",
    ticketId: "5",
  },
  {
    date: "2022/02/12",
    // status: "Delivered",
    firstParty: "CEVA",
    consigneeName: "FRANKE",
    consigneeAddress: "224 Wilson Avenue",
    // lastAssigned: "Rahul",
    barcodeNumber: "DG104-123456",
    shipper: "Amazon",
    pickup: "1",
    ticketId: "6",
  },
];
